In [1]:
import numpy as np

a = np.random.randint(1,100,15)

np.sort(a)[::-1]

array([97, 89, 86, 80, 73, 68, 65, 64, 62, 48, 35, 30, 11,  6,  4])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[98, 42, 99,  4],
       [82, 76,  1, 80],
       [31, 34, 20, 40],
       [85, 10, 96, 76],
       [30, 94, 17, 10],
       [78, 80, 98, 49]])

In [3]:
np.sort(b,axis=0)

array([[30, 10,  1,  4],
       [31, 34, 17, 10],
       [78, 42, 20, 40],
       [82, 76, 96, 49],
       [85, 80, 98, 76],
       [98, 94, 99, 80]])

In [4]:
np.append(a,200)

array([ 35,  11,  89,  68,  73,  30,   6,  48,  80,   4,  64,  97,  65,
        62,  86, 200])

In [5]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[98.        , 42.        , 99.        ,  4.        ,  0.371964  ],
       [82.        , 76.        ,  1.        , 80.        ,  0.79534312],
       [31.        , 34.        , 20.        , 40.        ,  0.48930975],
       [85.        , 10.        , 96.        , 76.        ,  0.75788096],
       [30.        , 94.        , 17.        , 10.        ,  0.25087047],
       [78.        , 80.        , 98.        , 49.        ,  0.71185942]])

In [6]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

np.concatenate((c,d),axis=0)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [9]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [10]:
np.where(a>50) #returns index

(array([ 2,  3,  4,  8, 10, 11, 12, 13, 14], dtype=int64),)

In [14]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([35, 11,  0,  0,  0, 30,  6, 48,  0,  4,  0,  0,  0,  0,  0])

In [18]:
np.argmax(a) #returns the maximum element within the given axis

11

In [19]:
np.cumsum(a)

array([ 35,  46, 135, 203, 276, 306, 312, 360, 440, 444, 508, 605, 670,
       732, 818])

In [20]:
#numpy.percentile() function used to compute the nth percentile of the given data (array elements) along the specified axis. 
np.percentile(a,50)

64.0

In [21]:
np.median(a)

64.0

In [22]:
np.histogram(a,bins=[0,50,100]) 

(array([6, 9], dtype=int64), array([  0,  50, 100]))

In [23]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [25]:
items = [10,20,30,40,50,60,70,80,90,100] #searches multiple items in a given array

a[np.isin(a,items)]

array([30, 80])

In [26]:
np.flip(a) #flips the element along a given axis

array([86, 62, 65, 97, 64,  4, 80, 48,  6, 30, 73, 68, 89, 11, 35])

In [35]:
a.put([0,1],[101,12])
print(a)

[101  12  89  68  73  30   6  48  80   4  64  97  65  62  86]


In [36]:
np.delete(a,[0,2,4])

array([12, 68, 30,  6, 48, 80,  4, 64, 97, 65, 62, 86])

In [37]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [38]:
np.intersect1d(m,n)

array([3, 4, 5])

In [39]:
np.setdiff1d(n,m)

array([6, 7])

In [40]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [41]:
np.clip(a,a_min=25,a_max=75)

array([75, 25, 75, 68, 73, 30, 25, 48, 75, 25, 64, 75, 65, 62, 75])

In [43]:
d = np.array([[1,2,3,4,5,6]])
d

array([[1, 2, 3, 4, 5, 6]])

In [44]:
np.squeeze(d)

array([1, 2, 3, 4, 5, 6])

In [ ]:
#np.abs
#np.round

In [45]:
np.tile(1,(3,3))

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [53]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(21,30).reshape(3,3)

print(np.einsum('ii->i',a))
print(np.einsum('ji',a))
print(np.einsum('ij,jk',a,b))
print(np.einsum('ii',a))



[1 5 9]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[150 156 162]
 [366 381 396]
 [582 606 630]]
15
